@echo off
IF "%1"=="test" (
    echo ==> Running Unit Tests...
    go test ./internal/...
) ELSE IF "%1"=="run" (
    echo ==> Building and Launching Sidecar...
    go build -o sidecar.exe ./cmd/sidecar
    sidecar.exe
) ELSE (
    echo ==> Building ACF Sidecar...
    go build -o sidecar.exe ./cmd/sidecar
)